//******************************************************
//EXPERIENCIAS

// {
//     id: "exp-ejemplo",
//     type: "experiencia", // Identificador de tipo
//     name: "Experiencia de Ejemplo",
//     city: "Lugo",
//     province: "Lugo",
//     zonas: ["zona-ejemplo2", ],
//     price: "Desde 00€",
//     description: "Descripcion de ejemplo",
//     urlReservaDirecta: "https://www.web-externa-de-reserva.com/",
//     image: "../../assets/imagen-ejemplo1.jpg",
//     heroImage: "../assets/imagen-ejemplo2.jpg",
//     tags: ["Tradicional", "Familiar", "Gastronómico"],
//     link: "experiencias/plantilla-experiencias.html",
//     mapa: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d47271.23966661299!2d-8.766625358427472!3d42.22614533698503!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd2f621461b2c193%3A0x7b441dad174bd49f!2sVigo%2C%20Pontevedra!5e0!3m2!1ses!2ses!4v1777890530999!5m2!1ses!2ses",
    
//     fotos: [ 
//       { url: "../../assets/imagen-ejemplo3.jpg", texto: "" },
//       { url: "../../assets/imagen-ejemplo3.jpg", texto: "Pie de página opcional" },
//       { url: "../../assets/imagen-ejemplo3.jpg", texto: "" },
//       { url: "../../assets/imagen-ejemplo3.jpg", texto: "Pie de página opcional" },
//      ],
//     infoAdicional: [ 
//       { icono: "info",
//         titulo: "Más Información:",
//         desc: "Aqui se pondría muchas más información sobre esta actividad..." }
//       ]
//   },

const experiences = [
   {
    id: "exp-amextreme-padron",
    type: "experiencia", // Identificador de tipo
    name: "Amextreme Aventura",
    city: "Padrón",
    province: "A Coruña",
    zonas: ["zona-ejemplo", ],
    price: "Desde 20€",
    description: "Amextreme Aventura, con su base principal situada en Ribadulla, es una entidad líder en turismo activo que posiciona a Galicia como un destino vacacional de referencia. La empresa ofrece deportes de aventura para personas de todas las edades para vivir Galicia de una forma diferente. La combinación de ejercicio, superación y aprendizaje en el medio natural, ofreciendo además opciones de deporte de aventura para hacer con toda la familia. ",
    urlReservaDirecta: "",
    image: "../../assets/imagen-ejemplo1.jpg",
    heroImage: "../assets/imagen-ejemplo2.jpg",
    tags: ["Montaña", "Familiar", "Aventura"],
    link: "experiencias/plantilla-experiencias.html",
    mapa: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2929.931763207986!2d-8.597326923481729!3d42.747495910535896!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd2f044784abca63%3A0x1e6c2705111bb82a!2sAMEXTREME%20AVENTURA!5e0!3m2!1ses!2ses!4v1778838835341!5m2!1ses!2ses",
    
    fotos: [ 
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "" },
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "Pie de página opcional" },
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "" },
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "Pie de página opcional" },
     ],
    infoAdicional: [ 
      { icono: "kayaking",
        titulo: "Rafting:",
        desc: "Una actividad de descenso por los ríos Ulla y Miño que se hace remando en equipo para dirigir la balsa, combinando esfuerzo y consideración." },
      { icono: "rowing",
        titulo: "Kayak:",
        desc: "El servicio de Kayak permite navegar de forma autónoma, ya que no tiene ruta guiada." },
      { icono: "mountain_steam",
        titulo: "Barranquismo:",
        desc: "Es una apasionante aventura." },
      { icono: "mountain_flag",
        titulo: "Escalada y espeleo:",
        desc: "La escalada es una actividad de progresión vertical en roca que requiere técnicas de agarre y equilibrio, mientras que la espeleología consiste en la exploración técnica de cuevas y cavidades naturales que incluye niveles de iniciación." },
      { icono: "target",
        titulo: "Paintball:",
        desc: "Deporte perfecto para hacer en familia. " },
      { icono: "sprint",
        titulo: "Puenting:",
        desc: "Experiencia de salto al vacío desde un puente utilizando sistemas técnicos de cuerdas y seguridad para los más atrevidos." },
      { icono: "dictionary",
        titulo: "Formación",
        desc: "Como centro de formación especializada, imparten cursos de rescate en Galicia en ríos y riadas nivel I y II, enfocados a la capacitación técnica profesional." },
      { icono: "info",
        titulo: "Más Información",
        desc: "La empresa integra en su logística el Camino de Santiago y la organización de campamentos, destacando los campamentos de Xacobeo y Aventura y finalmente, facilitan la experiencia completa mediante la recomendación de alojamientos, garantizando una logística profesional y segura en cada disciplina. " },
      ]
  },
   {
    id: "exp-amextreme-bertamirans",
    type: "experiencia", // Identificador de tipo
    name: "Amextreme Aventura",
    city: "Bertamiráns",
    province: "A Coruña",
    zonas: ["zona-ejemplo", ],
    price: "Desde 20€",
    description: "Amextreme Aventura, con su base principal situada en Ribadulla, es una entidad líder en turismo activo que posiciona a Galicia como un destino vacacional de referencia. La empresa ofrece deportes de aventura para personas de todas las edades para vivir Galicia de una forma diferente. La combinación de ejercicio, superación y aprendizaje en el medio natural, ofreciendo además opciones de deporte de aventura para hacer con toda la familia. ",
    image: "../../assets/imagen-ejemplo1.jpg",
    heroImage: "../assets/imagen-ejemplo2.jpg",
    tags: ["Montaña", "Familiar", "Aventura"],
    link: "experiencias/plantilla-experiencias.html",
    mapa: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d93672.50812030087!2d-8.70789264349255!3d42.80386721047291!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd2efd4c4f234743%3A0x935931b6c7d26f6c!2sDeportes%20de%20Aventura%20A%20Coru%C3%B1a%3A%20AMEXTREME%20AVENTURA!5e0!3m2!1ses!2ses!4v1778839803069!5m2!1ses!2ses",
    
    fotos: [ 
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "" },
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "Pie de página opcional" },
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "" },
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "Pie de página opcional" },
     ],
    infoAdicional: [ 
      { icono: "kayaking",
        titulo: "Rafting:",
        desc: "Una actividad de descenso por los ríos Ulla y Miño que se hace remando en equipo para dirigir la balsa, combinando esfuerzo y consideración." },
      { icono: "rowing",
        titulo: "Kayak:",
        desc: "El servicio de Kayak permite navegar de forma autónoma, ya que no tiene ruta guiada." },
      { icono: "mountain_steam",
        titulo: "Barranquismo:",
        desc: "Es una apasionante aventura." },
      { icono: "mountain_flag",
        titulo: "Escalada y espeleo:",
        desc: "La escalada es una actividad de progresión vertical en roca que requiere técnicas de agarre y equilibrio, mientras que la espeleología consiste en la exploración técnica de cuevas y cavidades naturales que incluye niveles de iniciación." },
      { icono: "target",
        titulo: "Paintball:",
        desc: "Deporte perfecto para hacer en familia. " },
      { icono: "sprint",
        titulo: "Puenting:",
        desc: "Experiencia de salto al vacío desde un puente utilizando sistemas técnicos de cuerdas y seguridad para los más atrevidos." },
      { icono: "dictionary",
        titulo: "Formación",
        desc: "Como centro de formación especializada, imparten cursos de rescate en Galicia en ríos y riadas nivel I y II, enfocados a la capacitación técnica profesional." },
      { icono: "info",
        titulo: "Más Información",
        desc: "La empresa integra en su logística el Camino de Santiago y la organización de campamentos, destacando los campamentos de Xacobeo y Aventura y finalmente, facilitan la experiencia completa mediante la recomendación de alojamientos, garantizando una logística profesional y segura en cada disciplina. " },
      ]
  },
   {
    id: "exp-sailway",
    type: "experiencia", // Identificador de tipo
    name: "Sailway",
    city: "Vigo",
    province: "Pontevedra",
    zonas: ["zona-ejemplo", ],
    price: "Desde 70€",
    description: "Sailway, con base en el Real Club Náutico de Vigo , es una organización integral del sector náutico que destaca por su operatividad técnica en la gestión de servicios marítimos. Su infraestructura está diseñada para cubrir todas las facetas del mundo naútico, posicionándose como un centro logístico multidisciplinar donde la formación, el turismo activo y la comercialización de embarcaciones convergen para ofrecer una solución completa en el entorno de la Ría de Vigo. ",
    image: "../../assets/imagen-ejemplo1.jpg",
    heroImage: "../assets/imagen-ejemplo2.jpg",
    tags: ["Relajación", "Familiar", "Aventura"],
    link: "experiencias/plantilla-experiencias.html",
    mapa: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2953.73031297825!2d-8.722748223501787!3d42.24157424257831!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd2f62407d7de8f3%3A0xc8b960fb30f591e1!2sSailway!5e0!3m2!1ses!2ses!4v1778839951133!5m2!1ses!2ses",
    
    fotos: [ 
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "" },
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "Pie de página opcional" },
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "" },
      { url: "../../assets/imagen-ejemplo3.jpg", texto: "Pie de página opcional" },
     ],
    infoAdicional: [ 
      { icono: "dictionary",
        titulo: "Academia de Vela y Titulaciones:",
        desc: "Como centro de formación especializado, Sailway funciona como una academia de vela dedicada a la instrucción y obtención de titulaciones náuticas. Su metodología combina el rigor técnico con la formación práctica, permitiendo a los alumnos desde iniciarse en las maniobras básicas hasta obtener las licencias oficiales necesarias para el gobierno de embarcaciones de recreo, garantizando siempre una navegación segura y profesional." },
      { icono: "sailing",
        titulo: "Experiencias turísticas:",
        desc: "La compañía organiza diversas experiencias turísticas diseñadas para disfrutar del mar y descubrir el litoral desde una perspectiva diferente. Estas actividades permiten a los usuarios disfrutar de jornadas de navegación mediante una logística organizada y profesional, convirtiendo el turismo náutico en una opción de ocio accesible para los visitantes que desean explorar la costa gallega a bordo de una embarcación. " },
      { icono: "anchor",
        titulo: "Venta de Barcos y Accesorios:",
        desc: "Más allá de las actividades recreativas, Sailway actúa como un punto de venta especializado en la comercialización de barcos y accesorios náuticos. Ofrecen asesoramiento técnico para la adquisición de naves y suministran el equipamiento necesario para el mantenimiento y la mejora de las embarcaciones, asegurando que cada cliente disponga de los componentes técnicos adecuados para su actividad en el mar. " },
      { icono: "news",
        titulo: "Blog y Actualidad:",
        desc: "La organización mantiene un blog especializado de actualización periódica donde comparten noticias de actualidad náutica, consejos de seguridad y curiosidad del sector." },
      { icono: "info",
        titulo: "Más Información",
        desc: "Sailway ha logrado centralizar en un mismo espacio la formación académica, la venta de material técnico y el disfrute recreativo, permitiendo que tanto el turista que busca una experiencia puntual como el patrón que necesita accesorios para su propio barco encuentren una respuesta profesional y experta en el puerto de Vigo. Sailway garantiza así una logística impecable, consolidándose como el aliado técnico perfecto para vivir y entender el mar con total profesionalidad. " },
    
      ]
  },
];
